// src/worker.ts を「外部依存のない自己完結IIFEバンドル」にコンパイルし、その文字列を
// src/worker-inline.generated.ts へ書き出す（gitignore対象・毎ビルド/テスト前に再生成する
// 使い捨てファイル）。
//
// なぜ二段階ビルドか: index.ts が Blob URL で Worker を起動する設計上、Worker本体の
// ソースは「文字列」として index.ts のバンドルに埋め込む必要がある。しかし worker.ts は
// `@elchika-inc/moonqr/decode` と `./multiscale.js` に依存しており、Blob URL 経由で起動
// された Worker のコンテキストからはこれらの module specifier を解決できない（blob: origin
// にはファイルシステム上のnode_modulesが存在しない）。そのため worker.ts 単体を先に
// フルバンドル（外部依存ゼロ）し、その結果を index.ts が「ただの文字列定数」として
// import できるようにしている。
//
// format:"iife" を選ぶ理由: `type:"module"` Worker はSafari等での対応状況にばらつきが
// あった時期が長く、クラシックWorker（非module）の方が互換性が高い。フルバンドル済み
// なのでimport文が残らず、classic worker（`new Worker(url)`、type指定なし）で問題なく
// 動く。
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));

const result = await build({
  entryPoints: [`${packageRoot}src/worker.ts`],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  logLevel: "silent",
});

const output = result.outputFiles[0];
if (!output) {
  throw new Error("build-worker: esbuild produced no output file for src/worker.ts");
}

const banner = "// AUTO-GENERATED by scripts/build-worker.mjs — DO NOT EDIT (not committed; regenerated by `build`/`test:unit`)\n";
const contents = `${banner}export const WORKER_SOURCE: string = ${JSON.stringify(output.text)};\n`;
writeFileSync(`${packageRoot}src/worker-inline.generated.ts`, contents);
